import type {
  AppUpdateState,
  AppSettings,
  AutoCaptureState,
  AudioState,
  CaptureConfig,
  CaptureCapabilities,
  CaptureRuntime,
  CaptureStorage,
  Clip,
  ButtonAssignmentBinding,
  Device,
  EngineStatus,
  GameDetectionState,
  ModuleManifest,
  PerformanceSnapshot,
  SystemSnapshot,
} from './contracts';

function previewBinding(
  buttonId: string,
  label: string,
  slot: string,
  currentActionId: string,
  calloutSide: 'left' | 'right',
  order: number,
  x: number,
  y: number,
): ButtonAssignmentBinding {
  return {
    buttonId,
    slotId: `g502x-plus_${slot}_m1`,
    currentActionId,
    hotspot: {
      id: buttonId,
      label,
      position: { x, y },
      calloutSide,
      order,
      capability: 'button-assignment',
    },
  };
}
import {
  createDefaultChannelProcessing,
  createNaturalMicrophoneProcessors,
  defaultAudioPathPresets,
} from './audio-presets';

const now = () => new Date().toISOString();

export const defaultModules: ModuleManifest[] = [
  {
    id: 'device.razer-huntsman',
    name: 'Razer Huntsman',
    description: 'Native low-frequency lighting controls and honest capability reporting for Huntsman analog keyboards.',
    version: '0.1.0',
    kind: 'device',
    sizeMb: 0.2,
    installed: true,
    enabled: true,
    official: true,
    restartRequired: false,
    capabilities: ['keyboard', 'firmware', 'lighting'],
    vendors: ['1532'],
    source: 'bundled',
  },
  {
    id: 'device.hyperx-quadcast',
    name: 'HyperX QuadCast',
    description: 'QuadCast, QuadCast S, and QuadCast 2 controls through one capability module.',
    version: '0.1.0',
    kind: 'device',
    sizeMb: 1.2,
    installed: true,
    enabled: true,
    official: true,
    restartRequired: false,
    capabilities: ['microphone', 'gain', 'monitoring', 'lighting', 'firmware'],
    vendors: ['0951'],
    source: 'bundled',
  },
  {
    id: 'device.logitech-hidpp',
    name: 'Logitech HID++',
    description: 'Self-describing Logitech mouse and keyboard support without one package per model.',
    version: '0.1.0',
    kind: 'device',
    sizeMb: 1.8,
    installed: true,
    enabled: true,
    official: true,
    restartRequired: false,
    capabilities: ['mouse', 'dpi', 'polling-rate', 'buttons', 'battery', 'profiles'],
    vendors: ['046d'],
    source: 'bundled',
  },
  {
    id: 'capability.replay',
    name: 'Instant Replay',
    description: 'Isolated capture process with a disk-backed rolling buffer and hardware encoder selection.',
    version: '0.1.0',
    kind: 'capture',
    sizeMb: 84,
    installed: true,
    enabled: false,
    official: true,
    restartRequired: false,
    capabilities: ['display-capture', 'window-capture', 'replay-buffer', 'clips'],
    vendors: [],
    source: 'bundled',
  },
  {
    id: 'capability.audio-router',
    name: 'Audio Router',
    description: 'Game, chat, media, and aux buses with independent personal, stream, and clip mixes.',
    version: '0.1.0',
    kind: 'audio',
    sizeMb: 11.6,
    installed: true,
    enabled: false,
    official: true,
    restartRequired: false,
    capabilities: ['audio-buses', 'chatmix', 'microphone-dsp', 'stream-mix'],
    vendors: [],
    source: 'bundled',
  },
  {
    id: 'device.steelseries-hid',
    name: 'SteelSeries Devices',
    description: 'Optional SteelSeries HID support without installing the GG suite.',
    version: '0.0.1',
    kind: 'device',
    sizeMb: 2.4,
    installed: false,
    enabled: false,
    official: true,
    restartRequired: false,
    capabilities: ['mouse', 'keyboard', 'headset', 'lighting'],
    vendors: ['1038'],
    source: 'bundled',
  },
  {
    id: 'integration.obs',
    name: 'OBS Integration',
    description: 'Expose clip, stream mix, and scene actions through OBS WebSocket.',
    version: '0.0.1',
    kind: 'integration',
    sizeMb: 0.7,
    installed: false,
    enabled: false,
    official: false,
    restartRequired: false,
    capabilities: ['obs-websocket', 'scene-actions'],
    vendors: [],
    source: 'bundled',
  },
];

export const defaultDevices: Device[] = [
  {
    id: 'logitech-g502x-plus-1',
    moduleId: 'device.logitech-hidpp',
    displayName: 'G502 X Plus',
    kind: 'mouse',
    connected: true,
    identity: {
      manufacturer: 'Logitech',
      productFamily: 'G502',
      model: 'G502 X Plus',
      variant: 'white',
      colorway: 'White',
      connection: 'wireless',
      connectionLabel: 'LIGHTSPEED',
      vendorId: 0x046d,
      productId: 0x4099,
      transportProductId: 0xc547,
      serialNumber: 'PREVIEW-G502X',
      productString: 'G502 X PLUS',
    },
    variantResolution: {
      confidence: 'hardware',
      source: 'Logitech DEVIO extended model',
      evidence: 'extendedModel 1',
    },
    asset: {
      key: 'logitech-g502-x-plus-white',
      matchedBy: 'exact-variant',
      source: 'bundled-official',
    },
    capabilities: {
      battery: {
        percentage: 82,
        charging: false,
        fullyCharged: false,
        estimatedMinutesRemaining: 2_820,
        updatedAt: Date.now(),
      },
      dpi: {
        writable: true,
        min: 100,
        max: 25_600,
        step: 50,
        stages: [800, 1_600, 3_200],
        activeDpi: 1_600,
        defaultDpi: 800,
        shiftDpi: 800,
        maxStages: 5,
        profileMode: 'software',
      },
      reportRate: {
        writable: true,
        value: 1_000,
        supportedRates: [125, 250, 500, 1_000],
        profileMode: 'software',
      },
      buttonAssignments: {
        writable: true,
        profileMode: 'software',
        availableActions: [
          { id: 'mouse.primary-click', label: 'Left click', category: 'mouse', searchTerms: ['primary click', 'mb1'] },
          { id: 'mouse.secondary-click', label: 'Right click', category: 'mouse', searchTerms: ['secondary click', 'mb2'] },
          { id: 'mouse.middle-click', label: 'Middle click', category: 'mouse', searchTerms: ['wheel press', 'mb3'] },
          { id: 'mouse.back', label: 'Back', category: 'mouse', searchTerms: ['browser back', 'mb4'] },
          { id: 'mouse.forward', label: 'Forward', category: 'mouse', searchTerms: ['browser forward', 'mb5'] },
          { id: 'mouse.dpi-up', label: 'DPI up', category: 'mouse', searchTerms: ['sensitivity increase'] },
          { id: 'mouse.dpi-down', label: 'DPI down', category: 'mouse', searchTerms: ['sensitivity decrease'] },
          { id: 'mouse.dpi-shift', label: 'DPI shift', category: 'mouse', searchTerms: ['sniper', 'temporary dpi'] },
        ],
        bindings: [
          previewBinding('primary', 'Primary click', 'g1', 'mouse.primary-click', 'left', 0, 44, 23),
          previewBinding('back', 'Back', 'g4', 'mouse.back', 'left', 1, 34, 55),
          previewBinding('dpi-shift', 'DPI shift', 'g5', 'mouse.dpi-shift', 'left', 2, 36, 43),
          previewBinding('secondary', 'Secondary click', 'g2', 'mouse.secondary-click', 'right', 0, 60, 23),
          previewBinding('wheel', 'Wheel press', 'g3', 'mouse.middle-click', 'right', 1, 53, 35),
          previewBinding('forward', 'Forward', 'g6', 'mouse.forward', 'right', 2, 35, 49),
        ],
      },
      lighting: {
        writable: true,
        enabled: true,
        activeEffectId: 'static',
        availableEffects: [
          { id: 'static', label: 'Static', controls: ['color', 'zones', 'brightness'] },
          { id: 'breathing', label: 'Breathing', controls: ['color', 'brightness', 'speed'] },
          { id: 'cycle', label: 'Color cycle', controls: ['brightness', 'speed'] },
          { id: 'wave', label: 'Color wave', controls: ['brightness', 'speed', 'direction'] },
          { id: 'ripple', label: 'Ripple', controls: ['color', 'speed'] },
        ],
        color: '#7dd3fc',
        colorWritable: true,
        brightness: 75,
        brightnessWritable: true,
        speed: 50,
        speedWritable: false,
        direction: 'right',
        availableDirections: ['cycle', 'left', 'right', 'up', 'down', 'in', 'out', 'center-in', 'center-out'],
        directionWritable: false,
        zones: [
          { id: 'zone-1', label: 'Zone 1', color: '#7dd3fc', colorWritable: true },
          { id: 'zone-2', label: 'Zone 2', color: '#a78bfa', colorWritable: true },
          { id: 'zone-3', label: 'Zone 3', color: '#f472b6', colorWritable: true },
          { id: 'zone-4', label: 'Zone 4', color: '#fb7185', colorWritable: true },
          { id: 'zone-5', label: 'Zone 5', color: '#fbbf24', colorWritable: true },
          { id: 'zone-6', label: 'Zone 6', color: '#34d399', colorWritable: true },
          { id: 'zone-7', label: 'Zone 7', color: '#22d3ee', colorWritable: true },
          { id: 'zone-8', label: 'Zone 8', color: '#60a5fa', colorWritable: true },
        ],
        profiles: [],
        muteLinked: false,
        muteLinkedWritable: false,
        physicalEffectVerified: false,
        profileMode: 'software',
        source: 'software',
        state: 'unknown',
        stateReason: 'Preview data mirrors a device-reported LIGHTSYNC layout; physical output still requires connected-hardware confirmation.',
      },
      onboardMemory: {
        writable: true,
        enabled: false,
        activeProfile: 'PROFILE_1',
      },
    },
    settings: {},
  },
  {
    id: 'hyperx-quadcast2-1',
    moduleId: 'device.hyperx-quadcast',
    displayName: 'QuadCast 2',
    kind: 'microphone',
    connected: true,
    identity: {
      manufacturer: 'HyperX',
      productFamily: 'QuadCast',
      model: 'QuadCast 2',
      variant: 'default',
      connection: 'usb',
      vendorId: 0x03f0,
      productId: 0x07b4,
      interfaceProductIds: [0x07b4, 0x09af],
      serialNumber: 'PREVIEW-QUADCAST2',
      productString: 'HyperX QuadCast 2',
    },
    variantResolution: {
      confidence: 'fallback',
      source: 'No cosmetic SKU reported by hardware',
    },
    asset: {
      key: 'hyperx-quadcast-2',
      matchedBy: 'exact-model',
      source: 'bundled-official',
    },
    capabilities: {
      gain: true,
      monitoring: true,
      mute: true,
      muteState: {
        muted: false,
        source: 'hardware',
        updatedAt: new Date().toISOString(),
      },
      lighting: {
        writable: true,
        enabled: true,
        activeEffectId: 'solid',
        availableEffects: [
          { id: 'solid', label: 'Solid' },
          { id: 'breathing', label: 'Breathing' },
          { id: 'pulse', label: 'Pulse' },
        ],
        color: '#f20000',
        colorWritable: false,
        brightness: 72,
        brightnessWritable: true,
        speed: 50,
        speedWritable: true,
        profiles: [
          { id: 'broadcast', label: 'Broadcast', effectId: 'solid', brightness: 72, speed: 50 },
          { id: 'breathe', label: 'Breathe', effectId: 'breathing', brightness: 55, speed: 42 },
          { id: 'night', label: 'Night', effectId: 'solid', brightness: 25, speed: 50 },
          { id: 'custom', label: 'Custom', effectId: 'solid', brightness: 55, speed: 50 },
        ],
        activeProfileId: 'broadcast',
        muteLinked: true,
        muteLinkedWritable: true,
        state: 'maintained',
        physicalEffectVerified: false,
        profileMode: 'software',
        source: 'software',
      },
    },
    settings: {
      gain: 58,
      monitoring: 18,
      muteLed: true,
      lightingEnabled: true,
      lightingColor: '#f20000',
      lightingBrightness: 72,
      lightingEffect: 'solid',
      lightingSpeed: 50,
      lightingProfileId: 'broadcast',
      customLightingBrightness: 55,
      customLightingEffect: 'solid',
      customLightingSpeed: 50,
    },
  },
  {
    id: 'razer-huntsman-v2-analog-1',
    moduleId: 'device.razer-huntsman',
    displayName: 'Huntsman V2 Analog',
    kind: 'keyboard',
    connected: true,
    identity: {
      manufacturer: 'Razer',
      productFamily: 'Huntsman',
      model: 'Huntsman V2 Analog',
      variant: 'black',
      colorway: 'Black',
      connection: 'usb',
      connectionLabel: 'USB',
      hardwareRevision: '0106',
      vendorId: 0x1532,
      productId: 0x0266,
      interfaceProductIds: [0x0266],
      serialNumber: 'PREVIEW-HUNTSMAN-V2-ANALOG',
      productString: 'Razer Huntsman V2 Analog',
    },
    variantResolution: {
      confidence: 'product-id',
      source: 'Razer USB product ID',
      evidence: '1532:0266',
    },
    asset: {
      key: 'razer-huntsman-v2-analog',
      matchedBy: 'exact-model',
      source: 'bundled-official',
    },
    capabilities: {
      keyboard: {
        firmwareVersion: '1.06',
        pollingRateHz: 1_000,
        transport: 'native-hid',
        features: [
          { id: 'lighting', label: 'Quick lighting', summary: 'Brightness and device-firmware quick effects use the native HID control endpoint.', status: 'native' },
          { id: 'actuation', label: 'Per-key actuation', summary: 'Adjustable 1.5–3.6 mm actuation and two-stage inputs are supported by the keyboard.', status: 'synapse', unavailableReason: 'The actuation protocol is not safely documented or verified for direct writes yet.' },
          { id: 'analog', label: 'Analog input', summary: 'Selected keys can emulate joystick axes and controller triggers.', status: 'synapse', unavailableReason: 'Analog mapping remains owned by Synapse until its native profile format is verified.' },
          { id: 'mapping', label: 'Key mapping', summary: 'Remapping, macros, Hypershift, and analog controller bindings remain in Synapse.', status: 'synapse', unavailableReason: 'Switchboard does not write undocumented key maps or macro payloads.' },
          { id: 'rapid-input', label: 'Snap Tap', summary: 'Snap Tap is available for this keyboard through Synapse 4.', status: 'synapse', unavailableReason: 'Switchboard does not expose Snap Tap because no independent device command is verified for this model.' },
        ],
        gamingMode: { enabled: false, writable: true },
        onboardProfiles: {
          activeProfileId: '1',
          profiles: [{ id: '1', label: 'Profile 1' }, { id: '2', label: 'Profile 2' }],
          writable: true,
        },
        diagnostics: {
          protocol: 'Razer feature reports',
          endpoint: 'ready',
          lastSyncAt: '2026-08-27T00:00:00.000Z',
          reads: ['firmware', 'serial-number', 'brightness', 'lighting-effect', 'lighting-effects', 'gaming-mode', 'onboard-profiles', 'active-profile']
            .map((id) => ({ id, ok: true })),
        },
      },
      lighting: {
        writable: true,
        enabled: true,
        activeEffectId: 'spectrum',
        availableEffects: [
          { id: 'static', label: 'Static', controls: ['color', 'brightness'] },
          { id: 'breathing', label: 'Breathing', controls: ['color', 'brightness'] },
          { id: 'spectrum', label: 'Spectrum', controls: ['brightness'] },
          { id: 'reactive', label: 'Reactive', controls: ['color', 'brightness'] },
          { id: 'starlight', label: 'Starlight', controls: ['color', 'brightness'] },
          { id: 'wave-left', label: 'Wave left', controls: ['brightness'] },
          { id: 'wave-right', label: 'Wave right', controls: ['brightness'] },
        ],
        color: '#44aaff',
        colorWritable: true,
        brightness: 100,
        brightnessWritable: true,
        speedWritable: false,
        profiles: [],
        muteLinked: false,
        muteLinkedWritable: false,
        state: 'maintained',
        stateReason: 'Fixture: active effect and brightness were read back from keyboard firmware.',
        physicalEffectVerified: false,
        profileMode: 'software',
        source: 'firmware',
      },
    },
    settings: {
      lightingEnabled: true,
      lightingBrightness: 100,
      lightingEffect: 'spectrum',
      lightingColor: '#44aaff',
    },
  },
];

export const defaultAudio: AudioState = {
  enabled: false,
  outputDevice: '',
  microphoneDevice: '',
  sampleRate: 48000,
  mixes: [
    {
      id: 'personal',
      label: 'Personal',
      master: { gain: 1, enabled: true },
      buses: [
        { id: 'game', gain: 1, enabled: true },
        { id: 'chat', gain: 0.76, enabled: true },
        { id: 'media', gain: 0.42, enabled: true },
        { id: 'aux', gain: 1, enabled: true },
        { id: 'mic', gain: 0.92, enabled: true },
      ],
    },
    {
      id: 'stream',
      label: 'Stream',
      master: { gain: 1, enabled: true },
      buses: [
        { id: 'game', gain: 1, enabled: true },
        { id: 'chat', gain: 1, enabled: true },
        { id: 'media', gain: 0.8, enabled: true },
        { id: 'aux', gain: 0, enabled: false },
        { id: 'mic', gain: 1, enabled: true },
      ],
    },
    {
      id: 'clip',
      label: 'Clip',
      master: { gain: 1, enabled: true },
      buses: [
        { id: 'game', gain: 1, enabled: true },
        { id: 'chat', gain: 0.55, enabled: true },
        { id: 'media', gain: 0.75, enabled: true },
        { id: 'aux', gain: 0, enabled: false },
        { id: 'mic', gain: 1, enabled: true },
      ],
    },
  ],
  chatMix: 0.15,
  monitoring: 0.18,
  monitoringEnabled: false,
  monitoringDeviceId: '',
  buses: [
    { id: 'game', label: 'Game', enabled: true, appCount: 0, meter: 0.72, endpoint: 'Switchboard Audio - Gaming', deviceId: '' },
    { id: 'chat', label: 'Chat', enabled: true, appCount: 0, meter: 0.38, endpoint: 'Switchboard Audio - Chat', deviceId: '' },
    { id: 'media', label: 'Media', enabled: true, appCount: 0, meter: 0.21, endpoint: 'Switchboard Audio - Media', deviceId: '' },
    { id: 'aux', label: 'Aux', enabled: true, appCount: 0, meter: 0, endpoint: 'Switchboard Audio - Aux', deviceId: '' },
    { id: 'mic', label: 'Microphone', enabled: true, appCount: 0, meter: 0.56, endpoint: 'Switchboard Audio - Microphone', deviceId: '' },
  ],
  micProcessors: createNaturalMicrophoneProcessors(),
  channelProcessing: [
    createDefaultChannelProcessing('game'),
    createDefaultChannelProcessing('chat'),
    createDefaultChannelProcessing('media'),
  ],
  devices: [],
  applications: [],
  capabilities: {
    virtualChannels: 'unavailable',
    applicationRouting: 'unavailable',
    channelDsp: 'unavailable',
    microphoneDsp: 'unavailable',
    noiseSuppression: 'unavailable',
    realtimeMetering: 'unavailable',
    microphoneTest: 'unavailable',
    monitoring: 'unavailable',
    spatialAudio: 'unavailable',
  },
  host: null,
  pathPresets: structuredClone(defaultAudioPathPresets),
  activePresetIds: {
    game: 'game-flat',
    chat: 'chat-natural',
    media: 'media-flat',
    microphone: 'mic-natural-voice',
  },
};

export const defaultCaptureConfig: CaptureConfig = {
  enabled: false,
  source: 'automatic-game',
  sourceId: null,
  displayIndex: 0,
  fps: 60,
  resolution: '1440p',
  codec: 'h264',
  encoder: 'auto',
  quality: 4,
  replaySeconds: 60,
  includeMic: true,
  includeSystemAudio: true,
  includeCursor: false,
  hotkey: 'Ctrl+Shift+F10',
  clipsDirectory: null,
};

export const defaultCaptureRuntime: CaptureRuntime = {
  state: 'stopped',
  bufferedSeconds: 0,
  segmentCount: 0,
  replayCacheBytes: 0,
  observedBitrateBps: 0,
  encoderLabel: 'Not selected',
  backendLabel: 'Windows Graphics Capture',
  droppedFrames: 0,
  encodedFrames: 0,
  audioSyncCorrections: 0,
  activeSource: null,
  saveQueueDepth: 0,
  shortcutRegistered: false,
  reactionClipping: {
    state: 'disabled',
    inputLevelDb: -96,
    noiseFloorDb: -60,
    triggerThresholdDb: -18,
    reactionsDetected: 0,
    analyzedFrames: 0,
    analysisAverageMs: 0,
    cooldownRemainingSeconds: 0,
    lastReactionAt: null,
    message: null,
  },
};

export const defaultCaptureStorage: CaptureStorage = {
  clipsDirectory: '',
  cacheDirectory: '',
  availableBytes: 0,
  volumeTotalBytes: 0,
  volumeAvailableBytes: 0,
  clipsBytes: 0,
  replayCacheBytes: 0,
  lowSpace: false,
  criticalSpace: false,
};

export const defaultCaptureCapabilities: CaptureCapabilities = {
  backend: 'unavailable',
  encoders: [],
  codecs: ['h264'],
  maximumFps: 60,
  systemAudio: false,
  microphoneAudio: false,
  exclusiveFullscreen: false,
};

export const defaultAutoCapture: AutoCaptureState = {
  settings: {
    enabled: false,
    preRollSeconds: 20,
    postRollSeconds: 10,
    mergeNearbyEvents: true,
    mergeThresholdSeconds: 15,
    notifyWhenSaved: false,
    reactionClipping: {
      enabled: false,
      sensitivity: 'balanced',
      preRollSeconds: 20,
      postRollSeconds: 10,
      cooldownSeconds: 15,
    },
    games: {},
    dismissedAvailability: {},
  },
  providers: [],
  runtime: {
    state: 'disabled',
    activeGameId: null,
    activeProviderId: null,
    pendingCapture: null,
    eventsReceived: 0,
    eventsDeduplicated: 0,
    eventsIgnored: 0,
    clipsCreated: 0,
    lastEvent: null,
    lastError: null,
  },
};

export const defaultGameDetection: GameDetectionState = {
  capability: 'available',
  scanState: 'idle',
  games: [],
  lastScanAt: null,
};

export const defaultSettings: AppSettings = {
  uiScalePercent: 125,
  launchAtStartup: false,
  closeToTray: true,
  destroyRendererInTray: true,
  softwareRendering: false,
  automaticAppUpdates: true,
  automaticAppUpdateDownloads: true,
  installAppUpdatesOnNextStartup: true,
  automaticModuleUpdates: true,
  performanceGuard: true,
  diagnosticsRetentionDays: 7,
  telemetry: false,
  scanGamesAutomatically: true,
  clipEditorInspectorOpen: true,
  deviceAppearanceOverrides: {},
};

export const defaultAppUpdate: AppUpdateState = {
  capability: 'unavailable',
  status: 'unavailable',
  currentVersion: '0.6.0',
  availableVersion: null,
  downloadProgress: null,
  checkedAt: null,
  error: null,
  unavailableReason: 'Application updates are available only in an installed Windows build.',
};

export const stoppedEngines: EngineStatus[] = [
  {
    kind: 'audio',
    state: 'stopped',
    cpuPercent: 0,
    memoryMb: 0,
    uptimeSeconds: 0,
    updatedAt: now(),
  },
  {
    kind: 'capture',
    state: 'stopped',
    cpuPercent: 0,
    memoryMb: 0,
    uptimeSeconds: 0,
    updatedAt: now(),
  },
];

export const defaultPerformance: PerformanceSnapshot = {
  coreMemoryMb: 0,
  rendererMemoryMb: 0,
  totalMemoryMb: 0,
  residentMemoryMb: 0,
  totalCpuPercent: 0,
  activeProcesses: 1,
  budgetMemoryMb: 180,
  budgetCpuPercent: 0.7,
  sampledAt: null,
  guardState: 'collecting',
  warning: null,
};

export const seedClips: Clip[] = [];

export function createDefaultSnapshot(): SystemSnapshot {
  return {
    version: '0.6.0',
    prototypeMode: true,
    appUpdate: structuredClone(defaultAppUpdate),
    modules: structuredClone(defaultModules),
    devices: structuredClone(defaultDevices),
    engines: structuredClone(stoppedEngines),
    audio: structuredClone(defaultAudio),
    capture: {
      config: structuredClone(defaultCaptureConfig),
      runtime: structuredClone(defaultCaptureRuntime),
      storage: structuredClone(defaultCaptureStorage),
      capabilities: structuredClone(defaultCaptureCapabilities),
      sources: [],
      autoCapture: structuredClone(defaultAutoCapture),
    },
    clips: structuredClone(seedClips),
    clipReview: { reviewedThrough: 0 },
    gameDetection: structuredClone(defaultGameDetection),
    performance: structuredClone(defaultPerformance),
    settings: structuredClone(defaultSettings),
  };
}
