import type {
  AppSettings,
  AudioState,
  CaptureConfig,
  CaptureCapabilities,
  CaptureRuntime,
  CaptureStorage,
  Clip,
  ButtonAssignmentBinding,
  Device,
  EngineStatus,
  GameDetectionState,
  ModuleManifest,
  PerformanceSnapshot,
  SystemSnapshot,
} from './contracts';

function previewBinding(
  buttonId: string,
  label: string,
  slot: string,
  currentActionId: string,
  calloutSide: 'left' | 'right',
  order: number,
  x: number,
  y: number,
): ButtonAssignmentBinding {
  return {
    buttonId,
    slotId: `g502x-plus_${slot}_m1`,
    currentActionId,
    hotspot: {
      id: buttonId,
      label,
      position: { x, y },
      calloutSide,
      order,
      capability: 'button-assignment',
    },
  };
}
import {
  createDefaultChannelProcessing,
  createNaturalMicrophoneProcessors,
  defaultAudioPathPresets,
} from './audio-presets';

const now = () => new Date().toISOString();

export const defaultModules: ModuleManifest[] = [
  {
    id: 'device.hyperx-quadcast',
    name: 'HyperX QuadCast',
    description: 'QuadCast, QuadCast S, and QuadCast 2 controls through one capability module.',
    version: '0.1.0',
    kind: 'device',
    sizeMb: 1.2,
    installed: true,
    enabled: true,
    official: true,
    restartRequired: false,
    capabilities: ['microphone', 'gain', 'monitoring', 'lighting', 'firmware'],
    vendors: ['0951'],
  },
  {
    id: 'device.logitech-hidpp',
    name: 'Logitech HID++',
    description: 'Self-describing Logitech mouse and keyboard support without one package per model.',
    version: '0.1.0',
    kind: 'device',
    sizeMb: 1.8,
    installed: true,
    enabled: true,
    official: true,
    restartRequired: false,
    capabilities: ['mouse', 'dpi', 'polling-rate', 'buttons', 'battery', 'profiles'],
    vendors: ['046d'],
  },
  {
    id: 'capability.replay',
    name: 'Instant Replay',
    description: 'Isolated capture process with a disk-backed rolling buffer and hardware encoder selection.',
    version: '0.1.0',
    kind: 'capture',
    sizeMb: 84,
    installed: true,
    enabled: false,
    official: true,
    restartRequired: false,
    capabilities: ['display-capture', 'window-capture', 'replay-buffer', 'clips'],
    vendors: [],
  },
  {
    id: 'capability.audio-router',
    name: 'Audio Router',
    description: 'Game, chat, media, and aux buses with independent personal, stream, and clip mixes.',
    version: '0.1.0',
    kind: 'audio',
    sizeMb: 11.6,
    installed: true,
    enabled: false,
    official: true,
    restartRequired: false,
    capabilities: ['audio-buses', 'chatmix', 'microphone-dsp', 'stream-mix'],
    vendors: [],
  },
  {
    id: 'device.steelseries-hid',
    name: 'SteelSeries Devices',
    description: 'Optional SteelSeries HID support without installing the GG suite.',
    version: '0.0.1',
    kind: 'device',
    sizeMb: 2.4,
    installed: false,
    enabled: false,
    official: true,
    restartRequired: false,
    capabilities: ['mouse', 'keyboard', 'headset', 'lighting'],
    vendors: ['1038'],
  },
  {
    id: 'integration.obs',
    name: 'OBS Integration',
    description: 'Expose clip, stream mix, and scene actions through OBS WebSocket.',
    version: '0.0.1',
    kind: 'integration',
    sizeMb: 0.7,
    installed: false,
    enabled: false,
    official: false,
    restartRequired: false,
    capabilities: ['obs-websocket', 'scene-actions'],
    vendors: [],
  },
];

export const defaultDevices: Device[] = [
  {
    id: 'logitech-g502x-plus-1',
    moduleId: 'device.logitech-hidpp',
    displayName: 'G502 X Plus',
    kind: 'mouse',
    connected: true,
    identity: {
      manufacturer: 'Logitech',
      productFamily: 'G502',
      model: 'G502 X Plus',
      variant: 'white',
      colorway: 'White',
      connection: 'wireless',
      connectionLabel: 'LIGHTSPEED',
      vendorId: 0x046d,
      productId: 0x4099,
      transportProductId: 0xc547,
      serialNumber: 'PREVIEW-G502X',
      productString: 'G502 X PLUS',
    },
    variantResolution: {
      confidence: 'hardware',
      source: 'Logitech DEVIO extended model',
      evidence: 'extendedModel 1',
    },
    asset: {
      key: 'logitech-g502-x-plus-white',
      matchedBy: 'exact-variant',
      source: 'bundled-official',
    },
    capabilities: {
      battery: {
        percentage: 82,
        charging: false,
        fullyCharged: false,
        estimatedMinutesRemaining: 2_820,
        updatedAt: Date.now(),
      },
      dpi: {
        writable: true,
        min: 100,
        max: 25_600,
        step: 50,
        stages: [800, 1_600, 3_200],
        activeDpi: 1_600,
        defaultDpi: 800,
        shiftDpi: 800,
        maxStages: 5,
        profileMode: 'software',
      },
      reportRate: {
        writable: true,
        value: 1_000,
        supportedRates: [125, 250, 500, 1_000],
        profileMode: 'software',
      },
      buttonAssignments: {
        writable: true,
        profileMode: 'software',
        availableActions: [
          { id: 'mouse.primary-click', label: 'Left click', category: 'mouse', searchTerms: ['primary click', 'mb1'] },
          { id: 'mouse.secondary-click', label: 'Right click', category: 'mouse', searchTerms: ['secondary click', 'mb2'] },
          { id: 'mouse.middle-click', label: 'Middle click', category: 'mouse', searchTerms: ['wheel press', 'mb3'] },
          { id: 'mouse.back', label: 'Back', category: 'mouse', searchTerms: ['browser back', 'mb4'] },
          { id: 'mouse.forward', label: 'Forward', category: 'mouse', searchTerms: ['browser forward', 'mb5'] },
          { id: 'mouse.dpi-up', label: 'DPI up', category: 'mouse', searchTerms: ['sensitivity increase'] },
          { id: 'mouse.dpi-down', label: 'DPI down', category: 'mouse', searchTerms: ['sensitivity decrease'] },
          { id: 'mouse.dpi-shift', label: 'DPI shift', category: 'mouse', searchTerms: ['sniper', 'temporary dpi'] },
        ],
        bindings: [
          previewBinding('primary', 'Primary click', 'g1', 'mouse.primary-click', 'left', 0, 44, 23),
          previewBinding('back', 'Back', 'g4', 'mouse.back', 'left', 1, 34, 55),
          previewBinding('dpi-shift', 'DPI shift', 'g5', 'mouse.dpi-shift', 'left', 2, 36, 43),
          previewBinding('secondary', 'Secondary click', 'g2', 'mouse.secondary-click', 'right', 0, 60, 23),
          previewBinding('wheel', 'Wheel press', 'g3', 'mouse.middle-click', 'right', 1, 53, 35),
          previewBinding('forward', 'Forward', 'g6', 'mouse.forward', 'right', 2, 35, 49),
        ],
      },
      lighting: {
        writable: true,
        enabled: false,
        activeEffectId: 'solid',
        availableEffects: [{ id: 'solid', label: 'Static' }],
        color: '#ff1744',
        colorWritable: true,
        brightness: 75,
        brightnessWritable: true,
        speedWritable: false,
        profiles: [],
        muteLinked: false,
        muteLinkedWritable: false,
        physicalEffectVerified: false,
        profileMode: 'software',
        source: 'software',
      },
      onboardMemory: {
        writable: true,
        enabled: false,
        activeProfile: 'PROFILE_1',
      },
    },
    settings: {},
  },
  {
    id: 'hyperx-quadcast2-1',
    moduleId: 'device.hyperx-quadcast',
    displayName: 'QuadCast 2',
    kind: 'microphone',
    connected: true,
    identity: {
      manufacturer: 'HyperX',
      productFamily: 'QuadCast',
      model: 'QuadCast 2',
      variant: 'default',
      connection: 'usb',
      vendorId: 0x03f0,
      productId: 0x07b4,
      interfaceProductIds: [0x07b4, 0x09af],
      serialNumber: 'PREVIEW-QUADCAST2',
      productString: 'HyperX QuadCast 2',
    },
    variantResolution: {
      confidence: 'fallback',
      source: 'No cosmetic SKU reported by hardware',
    },
    asset: {
      key: 'hyperx-quadcast-2',
      matchedBy: 'exact-model',
      source: 'bundled-official',
    },
    capabilities: {
      gain: true,
      monitoring: true,
      mute: true,
      muteState: {
        muted: false,
        source: 'hardware',
        updatedAt: new Date().toISOString(),
      },
      lighting: {
        writable: true,
        enabled: true,
        activeEffectId: 'solid',
        availableEffects: [
          { id: 'solid', label: 'Solid' },
          { id: 'breathing', label: 'Breathing' },
          { id: 'pulse', label: 'Pulse' },
        ],
        color: '#f20000',
        colorWritable: false,
        brightness: 72,
        brightnessWritable: true,
        speed: 50,
        speedWritable: true,
        profiles: [
          { id: 'broadcast', label: 'Broadcast', effectId: 'solid', brightness: 72, speed: 50 },
          { id: 'breathe', label: 'Breathe', effectId: 'breathing', brightness: 55, speed: 42 },
          { id: 'night', label: 'Night', effectId: 'solid', brightness: 25, speed: 50 },
          { id: 'custom', label: 'Custom', effectId: 'solid', brightness: 55, speed: 50 },
        ],
        activeProfileId: 'broadcast',
        muteLinked: true,
        muteLinkedWritable: true,
        state: 'maintained',
        physicalEffectVerified: false,
        profileMode: 'software',
        source: 'software',
      },
    },
    settings: {
      gain: 58,
      monitoring: 18,
      muteLed: true,
      lightingEnabled: true,
      lightingColor: '#f20000',
      lightingBrightness: 72,
      lightingEffect: 'solid',
      lightingSpeed: 50,
      lightingProfileId: 'broadcast',
      customLightingBrightness: 55,
      customLightingEffect: 'solid',
      customLightingSpeed: 50,
    },
  },
];

export const defaultAudio: AudioState = {
  enabled: false,
  outputDevice: '',
  microphoneDevice: '',
  sampleRate: 48000,
  master: { gain: 1, enabled: true },
  chatMix: 0.15,
  monitoring: 0.18,
  monitoringEnabled: false,
  monitoringDeviceId: '',
  buses: [
    { id: 'game', label: 'Game', enabled: true, appCount: 0, gain: 1, muted: false, meter: 0.72, endpoint: 'Switchboard Audio - Gaming', deviceId: '' },
    { id: 'chat', label: 'Chat', enabled: true, appCount: 0, gain: 0.76, muted: false, meter: 0.38, endpoint: 'Switchboard Audio - Chat', deviceId: '' },
    { id: 'media', label: 'Media', enabled: true, appCount: 0, gain: 0.42, muted: false, meter: 0.21, endpoint: 'Switchboard Audio - Media', deviceId: '' },
    { id: 'aux', label: 'Aux', enabled: true, appCount: 0, gain: 1, muted: false, meter: 0, endpoint: 'Switchboard Audio - Aux', deviceId: '' },
    { id: 'mic', label: 'Microphone', enabled: true, appCount: 0, gain: 0.92, muted: false, meter: 0.56, endpoint: 'Switchboard Audio - Microphone', deviceId: '' },
  ],
  micProcessors: createNaturalMicrophoneProcessors(),
  channelProcessing: [
    createDefaultChannelProcessing('game'),
    createDefaultChannelProcessing('chat'),
    createDefaultChannelProcessing('media'),
  ],
  devices: [],
  applications: [],
  capabilities: {
    virtualChannels: 'unavailable',
    applicationRouting: 'unavailable',
    channelDsp: 'unavailable',
    microphoneDsp: 'unavailable',
    noiseSuppression: 'unavailable',
    realtimeMetering: 'unavailable',
    microphoneTest: 'unavailable',
    monitoring: 'unavailable',
    spatialAudio: 'unavailable',
  },
  host: null,
  pathPresets: structuredClone(defaultAudioPathPresets),
  activePresetIds: {
    game: 'game-flat',
    chat: 'chat-natural',
    media: 'media-flat',
    microphone: 'mic-natural-voice',
  },
};

export const defaultCaptureConfig: CaptureConfig = {
  enabled: false,
  source: 'automatic-game',
  sourceId: null,
  displayIndex: 0,
  fps: 60,
  resolution: '1440p',
  codec: 'h264',
  encoder: 'auto',
  quality: 4,
  replaySeconds: 60,
  includeMic: true,
  includeSystemAudio: true,
  includeCursor: false,
  hotkey: 'Ctrl+Shift+F10',
  clipsDirectory: null,
};

export const defaultCaptureRuntime: CaptureRuntime = {
  state: 'stopped',
  bufferedSeconds: 0,
  segmentCount: 0,
  replayCacheBytes: 0,
  observedBitrateBps: 0,
  encoderLabel: 'Not selected',
  backendLabel: 'Windows Graphics Capture',
  droppedFrames: 0,
  encodedFrames: 0,
  audioSyncCorrections: 0,
  activeSource: null,
  saveQueueDepth: 0,
  shortcutRegistered: false,
};

export const defaultCaptureStorage: CaptureStorage = {
  clipsDirectory: '',
  cacheDirectory: '',
  availableBytes: 0,
  volumeTotalBytes: 0,
  volumeAvailableBytes: 0,
  clipsBytes: 0,
  replayCacheBytes: 0,
  lowSpace: false,
  criticalSpace: false,
};

export const defaultCaptureCapabilities: CaptureCapabilities = {
  backend: 'unavailable',
  encoders: [],
  codecs: ['h264'],
  maximumFps: 60,
  systemAudio: false,
  microphoneAudio: false,
  exclusiveFullscreen: false,
};

export const defaultGameDetection: GameDetectionState = {
  capability: 'available',
  scanState: 'idle',
  games: [],
  lastScanAt: null,
};

export const defaultSettings: AppSettings = {
  launchAtStartup: false,
  closeToTray: true,
  destroyRendererInTray: true,
  automaticModuleUpdates: true,
  performanceGuard: true,
  diagnosticsRetentionDays: 7,
  telemetry: false,
  scanGamesAutomatically: true,
  clipEditorInspectorOpen: true,
  deviceAppearanceOverrides: {},
};

export const stoppedEngines: EngineStatus[] = [
  {
    kind: 'audio',
    state: 'stopped',
    cpuPercent: 0,
    memoryMb: 0,
    uptimeSeconds: 0,
    updatedAt: now(),
  },
  {
    kind: 'capture',
    state: 'stopped',
    cpuPercent: 0,
    memoryMb: 0,
    uptimeSeconds: 0,
    updatedAt: now(),
  },
];

export const defaultPerformance: PerformanceSnapshot = {
  coreMemoryMb: 44,
  rendererMemoryMb: 92,
  totalMemoryMb: 136,
  totalCpuPercent: 0.3,
  activeProcesses: 2,
  budgetMemoryMb: 240,
  budgetCpuPercent: 2,
};

export const seedClips: Clip[] = [];

export function createDefaultSnapshot(): SystemSnapshot {
  return {
    version: '0.1.0',
    prototypeMode: true,
    modules: structuredClone(defaultModules),
    devices: structuredClone(defaultDevices),
    engines: structuredClone(stoppedEngines),
    audio: structuredClone(defaultAudio),
    capture: {
      config: structuredClone(defaultCaptureConfig),
      runtime: structuredClone(defaultCaptureRuntime),
      storage: structuredClone(defaultCaptureStorage),
      capabilities: structuredClone(defaultCaptureCapabilities),
      sources: [],
    },
    clips: structuredClone(seedClips),
    gameDetection: structuredClone(defaultGameDetection),
    performance: structuredClone(defaultPerformance),
    settings: structuredClone(defaultSettings),
  };
}
